[package]
name = "simple-redis"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"
version = "1.87.0"

[dependencies]
anyhow = "1.0.97"
bytes = "1.10.1"
dashmap = "6.1.0"
enum_dispatch = "0.3.13"
lazy_static = "1.5.0"
thiserror = "2.0.12"
